#! /usr/bin/env -S python3 -u

import sys
import subprocess
import shutil
import tarfile

from pathlib import Path
from urllib.request import urlopen

ROOTDIR = Path(__file__).parent.parent

cppreference_tags = ROOTDIR / '.docbuild/cppreference-doxygen-web.tag.xml'

if not cppreference_tags.exists():
    print('Downloading cppreference tag file')
    with urlopen('https://github.com/PeterFeicht/cppreference-doc/releases/download/v20240610/html-book-20240610.tar.xz', timeout=10) as response:
        with tarfile.open(fileobj=response, mode="r|xz") as archive:
            while (member := archive.next()) is not None:
                if member.name == cppreference_tags.name:
                    archive.extract(member, cppreference_tags.parent, set_attrs=False)
                    break



(ROOTDIR / 'build/doxygen').mkdir(parents=True, exist_ok=True)
# if (ROOTDIR / 'build/sphinx').exists():
#     shutil.rmtree(ROOTDIR / 'build/sphinx')

res = subprocess.run(['doxygen', '.docbuild/Doxyfile'], cwd=ROOTDIR, check=False)
for tmp in (ROOTDIR / 'build/doxygen').glob('*.tmp'):
    tmp.unlink()
if res.returncode != 0:
    sys.exit(1)
# res = subprocess.run(['sphinx-build', '-M', 'html', '.docbuild', 'build/sphinx'], cwd=ROOTDIR)
# if res.returncode != 0:
#     sys.exit(1)
