name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  main:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Release Name
        shell: python
        run: |
          import os
          #ref = os.environ['GITHUB_REF']
          #name = ref[ref.rfind('/') + 1:]
          with open('lib/VERSION', 'r') as verFile:
            name = verFile.read().strip()
          with open(os.environ['GITHUB_ENV'], 'w') as env:
            print('RELEASE_NAME=' + name, file=env) 
        
      - name: Zip Headers
        run: tar -czf thinsqlitepp-${{ env.RELEASE_NAME }}.tar.gz --transform s/lib/thinsqlitepp/ lib

      - name: Make release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: false
          name: ${{ env.RELEASE_NAME }}
          body: ...edit me...
          files: |
            thinsqlitepp-${{ env.RELEASE_NAME }}.tar.gz
