name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  main:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get release Name
        uses: actions/github-script@v6
        with:
          script: |
            const tagName = context.ref.substring(context.ref.lastIndexOf('/') + 2)
            core.exportVariable('RELEASE_NAME', tagName)
        
      - name: Zip Headers
        run: tar -czf thinsqlitepp-${{ env.RELEASE_NAME }}.tar.gz --transform s/lib/thinsqlitepp/ lib

      - name: Make release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          name: ${{ env.RELEASE_NAME }}
          body: ...edit me...
          files: |
            thinsqlitepp-${{ env.RELEASE_NAME }}.tar.gz
