name: Test

on: 
  push:
    branches: 
      - '*'
      - '*/**'
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - 'LICENSE'
      - '.github/workflows/publish.yml'
      - '.github/workflows/make-docs.yml'
      - 'tools/**'
      - '.docbuild/**'


jobs:
  host:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: macos-latest
        - os: windows-latest

        - {os: ubuntu-latest, compiler: gcc, version: 11 }
        - {os: ubuntu-latest, compiler: gcc, version: 12 }
        - {os: ubuntu-latest, compiler: gcc, version: 13 }
        - {os: ubuntu-24.04, compiler: gcc, version: 14 }

        - {os: ubuntu-22.04, compiler: clang, version: 13 }
        - {os: ubuntu-22.04, compiler: clang, version: 14 }
        - {os: ubuntu-22.04, compiler: clang, version: 15 }
        - {os: ubuntu-22.04, compiler: clang, version: 16 }
        - {os: ubuntu-latest, compiler: clang, version: 17 }
        - {os: ubuntu-latest, compiler: clang, version: 18 }
        - {os: ubuntu-latest, compiler: clang, version: 19 }
        - {os: ubuntu-latest, compiler: clang, version: 20 }

    steps:
    - uses: actions/checkout@v4

    - name: System Setup
      shell: bash
      run: |
        if [[ '${{ matrix.os }}' == ubuntu-* ]]; then
          if [[ '${{ matrix.compiler }}' == 'clang' ]]; then
            wget https://apt.llvm.org/llvm.sh
            chmod u+x llvm.sh
            sudo ./llvm.sh ${{ matrix.version }} 
            sudo apt-get install -y clang-tools-${{ matrix.version }}
            echo "CC=clang-${{ matrix.version }}" >> $GITHUB_ENV
            echo "CXX=clang++-${{ matrix.version }}" >> $GITHUB_ENV
          fi

          if [[ '${{ matrix.compiler }}' == 'gcc' ]]; then
            sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
            sudo apt-get update
            sudo apt-get install -y gcc-${{ matrix.version }} g++-${{ matrix.version }}
            echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
            echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
          fi
        fi

    - name: Configure
      shell: bash
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release 

    - name: Build and Test
      shell: bash
      run: cmake --build build --config Release --target run-test

  container:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix: 
        container: [gcc:15.1]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install pre-requisites
      run: |
        apt-get update
        apt-get install -y ninja-build cmake

    - name: Configure
      shell: bash
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release 
  
    - name: Build and Test
      shell: bash
      run: cmake --build build --config Release --target run-test

  emscripten:
    runs-on: ubuntu-latest
    container: emscripten/emsdk:3.1.26

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pre-requisites
        run: |
          apt-get update
          apt-get install -y ninja-build
  
          export CMAKE_VERSION=3.24.4
          wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-Linux-x86_64.sh \
            -q -O /tmp/cmake-install.sh
          chmod u+x /tmp/cmake-install.sh
          /tmp/cmake-install.sh --skip-license --prefix=/usr
          rm -f /tmp/cmake-install.sh

      - name: Configure
        shell: bash
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake

      - name: Build and Test
        run: cmake --build build --config Release --target run-test


