name: Test

on: 
  push:
    branches: 
      - '*'
      - '*/**'
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - 'LICENSE'
      - '.github/workflows/publish.yml'
      - '.github/workflows/make-docs.yml'
      - 'tools/**'
      - '.docbuild/**'


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: macos-latest
        - os: windows-latest
        - {os: ubuntu-latest, compiler: gcc, version: 11 }
        - {os: ubuntu-latest, compiler: gcc, version: 12 }
        - {os: ubuntu-latest, compiler: gcc, version: 13 }
        - {os: ubuntu-24.04, compiler: gcc, version: 14 }
        - {os: ubuntu-latest, compiler: clang, version: 13 }
        - {os: ubuntu-latest, compiler: clang, version: 14 }
        - {os: ubuntu-latest, compiler: clang, version: 15 }
        - {os: ubuntu-latest, compiler: clang, version: 16 }
        - {os: ubuntu-latest, compiler: clang, version: 17 }
        - {os: ubuntu-latest, compiler: clang, version: 18 }

    steps:
    - uses: actions/checkout@v4

    - name: System Setup
      shell: bash
      run: |
        if [[ '${{ matrix.os }}' == ubuntu-* ]]; then
          if [[ '${{ matrix.compiler }}' == 'clang' ]]; then
            wget https://apt.llvm.org/llvm.sh
            chmod u+x llvm.sh
            sudo ./llvm.sh ${{ matrix.version }} 
            sudo apt-get install -y clang-tools-${{ matrix.version }}
            echo "CC=clang-${{ matrix.version }}" >> $GITHUB_ENV
            echo "CXX=clang++-${{ matrix.version }}" >> $GITHUB_ENV
          fi

          if [[ '${{ matrix.compiler }}' == 'gcc' ]]; then
            sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
            sudo apt-get update
            sudo apt-get install -y gcc-${{ matrix.version }} g++-${{ matrix.version }}
            echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
            echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
          fi
        fi

    - name: Configure
      shell: bash
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release 

    - name: Build and Test
      shell: bash
      run: cmake --build build --config Release --target run-test

  emscripten:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup EMSDK
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.26
          actions-cache-folder: 'emsdk-cache'

      - name: Build and Test
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
          cmake --build build --config Release --target run-test


